<?php
include_once 'public_html/clases/cUpload.php';
define ('UPLOAD_FOLDER',dirname(dirname(__FILE__)).'/uploads/');
/**
 * Extends cUpload to override move_uploaded_file and pass the test
 */
class _cUpload extends cUpload {
    function move_uploaded_file($filename, $destination)
    {
            return copy($filename, $destination);
    }  
}
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-16 at 17:17:34.
 */
class cUploadTest extends PHPUnit_Framework_TestCase {

    /**
     * @var cUpload
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        $_FILES = array('test' => array(
                        'name' => 'test.jpg',
                        'type' => 'image/jpeg',
                        'size' => 542,
                        'tmp_name' =>dirname(dirname(dirname(__FILE__))).'/source-test.jpg',
                        'error' => UPLOAD_ERR_OK));
        
       
        $this->object = new _cUpload($_FILES['test']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        @unlink(UPLOAD_FOLDER.'test.jpg');
    }
    /**
     * @covers cUpload::getError
     * 
     */
    public function testGetError() {
        
        $this->assertEquals(false, $this->object->getError());
    }
    /**
     * @covers cUpload::saveFile
     * 
     */
    public function testSaveFile() {
       
       $this->assertEquals(true, $this->object->saveFile('test', UPLOAD_FOLDER));
    }

    /**
     * @covers cUpload::isChange
     *
     */
    public function testIsChange() {
       $this->object->saveFile('test', UPLOAD_FOLDER);
       $this->assertInternalType('bool', $this->object->isChange());
    }

    /**
     * @covers cUpload::getFileName
     */
    public function testGetFileName() {
        $this->object->saveFile('test', UPLOAD_FOLDER);
        $this->assertEquals('test', $this->object->getFileName());
    }

}
