<?php
include_once 'public_html/clases/cViewimage.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-16 at 17:17:34.
 */
class cViewimageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var cViewimage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new cViewimage('source-test',dirname(dirname(dirname(__FILE__))).'/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers cViewimage::getUrl
     * 
     */
    public function testGetUrl() {
        
        $this->assertEquals('.'.dirname(dirname(dirname(__FILE__))).'/source-test.jpg', $this->object->getUrl());
    }

}
